# Generated by Django 5.2.6 on 2025-10-05 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('surname', models.CharField(max_length=64, verbose_name='фамилия')),
                ('patronimyc', models.CharField(max_length=64, verbose_name='отчество')),
                ('birth_date', models.DateField(verbose_name='дата рож')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='дата см')),
            ],
            options={
                'verbose_name': 'kniga',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='pereplet',
            field=models.CharField(choices=[('такие есть', [('t', 'твёрдый'), ('m', 'мягкий')]), ('а таких может не быть', [('s', 'средний')])], default='t', max_length=1, verbose_name='переплёт'),
        ),
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.TextField(help_text='напиши о книге', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=5, verbose_name='кол'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(default=5, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='автор'),
        ),
    ]
